app default {
	#debug = 8;
	#debug_file = opensc.log;
	reader_driver pcsc {
		# Connect to reader in exclusive mode?
		# Default: false
		#connect_exclusive = true;
		#
		# Enable pinpad if detected (PC/SC v2.0.2 Part 10)
		# Default: true
		enable_pinpad = true;
	}
	framework pkcs15 {
		# Default: `public` for static cards, `false` otherwise
		use_file_caching = false;
		# Use PIN caching?
		# Default: true
		use_pin_caching = false;
	}
}
